name: publish
on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install deps
        run: npm ci

      - name: test
        run: npm run test-run

      - name: build parser
        working-directory: git-commit-parser
        run: npx tsc -b

      - name: test build extension
        working-directory: extension
        run: npm run vscode:package

      - name: semantic-release
        if: github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # actual build extension (with correct version)
      - name: reference extension
        working-directory: extension
        # run: |
        #   npm run vscode:package
        #   echo "::set-output name=vsixPath::$(find . -name 'vscode-commit-pro-extension-*.vsix')"
        run: echo "::set-output name=vsixPath::$(find . -name 'vscode-commit-pro-extension-*.vsix')"

      # - name: Publish to Open VSX Registry
      #   uses: HaaLeo/publish-vscode-extension@v1
      #   with:
      #     pat: ${{ secrets.OPEN_VSX_TOKEN }}
      #     extensionFile: ${{ steps.referenceExtension.outputs.vsixPath }}

      # - name: Publish to Visual Studio Marketplace
      #   uses: HaaLeo/publish-vscode-extension@v1
      #   with:
      #     pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
      #     registryUrl: https://marketplace.visualstudio.com
      #     extensionFile: ${{ steps.referenceExtension.outputs.vsixPath }}

