name: publish
on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install deps
        run: npm ci

      - name: test
        run: npm run test-run

      - name: build parser
        working-directory: git-commit-parser
        run: npx tsc -b

      - name: test build extension
        working-directory: extension
        run: |
          npm run vscode:package
          rm vscode-commit-pro-extension-*.vsix
        # ⇧ clean up again, otherwise referencing won't work

      - name: semantic-release
        if: github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # actual build extension (with correct version)
      - name: reference extension
        id: referenceExtension
        run: echo "::set-output name=vsixPath::$(find . -name 'vscode-commit-pro-extension-*.vsix')"
